[cols="1,3",frame=none,grid=none]
|===
|Home
|link:https://github.com/heliconialabs/moving-abap-read-only-workloads-to-serverless[https://github.com/heliconialabs/moving-abap-read-only-workloads-to-serverless]

|License
|link:https://github.com/heliconialabs/moving-abap-read-only-workloads-to-serverless/blob/main/LICENSE[Creative Commons Attribution 4.0 International]

|Build
|{docdatetime}
|===

== Introduction

Sometimes microservices can help fulfilling business requirements, sometimes monoliths, both has its perils.

ABAP has traditionally only targeted monolithic applications, this paper suggests a multi-target setup where read-only ABAP code can be deployed to run on both a traditional ABAP stack and as a microservice on hyperscalers.

=== Setup

[plantuml]
....
skinparam monochrome true

cloud {
  database "SAP on\nAnyDB" as sap
}

cloud {
  database "Data Lake\non HANA" as lake

  card card [
    <b>Microservice</b>
    ----
    //abap-openapi//
    ----
    <u>Custom ABAP Logic</u>
    ----
    //open-abap//
    ----
    //transpiler runtime//
    ----
    //node-hdb//
  ]

  card -down-> lake : read
}


sap --> lake : SLT
....

https://www.sap.com/products/landscape-replication-server.html[SLT] replicates data to a data lake.

Data in the data lake is stored in https://en.wikipedia.org/wiki/Data_lake[raw format].

Custom ABAP logic runs as a microservice reading data from the data lake and can be accessed via standardized APIs.

=== Benefits

* API first
* Scaling up on cloud
* Scaling down on central SAP system
* Deploy changes independently


=== Multi target ABAP applications
[plantuml]
....
skinparam monochrome true

rectangle "ABAP Logic\nstored in git" as logic
logic -> logic: CI

cloud Steampunk {
  rectangle "ABAP Logic" as logic1
}

cloud "Embedded\nSteampunk" {
  rectangle "ABAP Logic" as logic2
}

cloud "ECC/S4" {
  rectangle "ABAP Logic" as logic3
}

cloud "Microservice" {
  rectangle "ABAP Logic" as logic4
}

logic -up-> logic1: Deploy
logic -up-> logic2: Deploy
logic -up-> logic3: Deploy
logic -up-> logic4: Deploy
....