[cols="1,3",frame=none,grid=none]
|===
|Home
|link:https://github.com/heliconialabs/moving-abap-read-only-workloads-to-serverless[https://github.com/heliconialabs/moving-abap-read-only-workloads-to-serverless]

|License
|link:https://github.com/heliconialabs/moving-abap-read-only-workloads-to-serverless/blob/main/LICENSE[Creative Commons Attribution 4.0 International]

|Build
|{docdatetime}
|===

== Introduction

Sometimes microservices can help fulfilling business requirements, sometimes monoliths, both has its perils.

ABAP has traditionally only targeted monolithic applications, this paper suggests a multi-target setup where read-only ABAP code can be deployed to run on both a traditional ABAP stack and as a microservice on hyperscalers.

=== Setup

[plantuml]
....
skinparam monochrome true

cloud {
  database "SAP on\nAnyDB" as sap
}

cloud {
  database "Data Lake\non HANA" as lake

  card card [
    <b>Microservice
    ----
    abap-openapi
    ----
    Custom ABAP Logic
    ----
    open-abap
    ----
    transpiler runtime
    ----
    node-hdb
  ]

  card -down-> lake : read
}


sap --> lake : SLT
....

data lake stored in raw format, https://en.wikipedia.org/wiki/Data_lake

=== Benefits

why

* API first
* Scaling up on cloud native
* Scaling down on central SAP system
* Deploy changes independently
